/**
 * compile.js — Design token compiler
 *
 * Reads brands/*.json and generates three output formats for each brand:
 *   compiled/{brand}.css   — CSS custom properties (:root { --token: value })
 *   compiled/{brand}.scss  — SCSS variable declarations ($token: value)
 *   compiled/{brand}.json  — Flat key→value map for programmatic consumption
 *
 * Usage:
 *   node compile.js       (run from tokens/ directory)
 *   npm run compile       (same, via package.json)
 *
 * Run this after editing any brands/*.json file and commit both the JSON
 * source and the compiled/ outputs.
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const brandsDir  = resolve(__dirname, 'brands')
const compiledDir = resolve(__dirname, 'brands', 'compiled')

mkdirSync(compiledDir, { recursive: true })

const brandFiles = readdirSync(brandsDir).filter(f => f.endsWith('.json'))

if (brandFiles.length === 0) {
  console.error('[compile] No brand JSON files found in brands/')
  process.exit(1)
}

for (const file of brandFiles) {
  const source = JSON.parse(readFileSync(resolve(brandsDir, file), 'utf8'))
  const { brand, tokens } = source

  if (!brand || !tokens) {
    console.error(`[compile] Skipping ${file}: missing "brand" or "tokens" field`)
    continue
  }

  const entries = Object.entries(tokens)

  // ── CSS custom properties ──────────────────────────────────────────────────
  const cssLines = [
    `/* ${brand} brand tokens */`,
    `/* generated by tokens/compile.js — edit brands/${brand}.json, not this file */`,
    `:root {`,
    ...entries.map(([k, v]) => `  --${k}: ${v};`),
    `}`,
    ``,
  ]
  if (source.light) {
    const lightEntries = Object.entries(source.light)
    cssLines.push(
      `/* light-mode overrides */`,
      `body.light {`,
      ...lightEntries.map(([k, v]) => `  --${k}: ${v};`),
      `}`,
      ``,
    )
  }
  writeFileSync(resolve(compiledDir, `${brand}.css`), cssLines.join('\n'), 'utf8')

  // ── SCSS variable declarations ─────────────────────────────────────────────
  const scssLines = [
    `// ${brand} brand tokens`,
    `// generated by tokens/compile.js — edit brands/${brand}.json, not this file`,
    ``,
    ...entries.map(([k, v]) => `$${k}: ${v};`),
    ``,
  ]
  writeFileSync(resolve(compiledDir, `${brand}.scss`), scssLines.join('\n'), 'utf8')

  // ── Flat JSON ──────────────────────────────────────────────────────────────
  const flat = { _brand: brand }
  for (const [k, v] of entries) flat[k] = v
  if (source.light) flat._light = { ...source.light }
  writeFileSync(
    resolve(compiledDir, `${brand}.json`),
    JSON.stringify(flat, null, 2) + '\n',
    'utf8'
  )

  console.log(`[compile] ${brand}: .css ✓  .scss ✓  .json ✓`)
}

console.log(`[compile] Done. ${brandFiles.length} brand(s) compiled to brands/compiled/`)
